# Generated by Django 5.2.18 on 2026-10-07 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0002_alter_projeto_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('prioridade', models.CharField(verbose_name=[('BA', 'Baixo'), ('NO', 'Normal/Médio'), ('AL', 'Alto'), ('UR', 'Urgente')])),
                ('concluido', models.BooleanField()),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefa', to='projetos.projeto')),
            ],
        ),
    ]
