# Generated by Django 5.2.18 on 2026-10-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(verbose_name=[('BA', 'Baixa'), ('NO', 'Normal/Média'), ('AL', 'Alta'), ('UR', 'Urgente')]),
        ),
    ]
