# Generated by Django 6.1.1 on 2026-10-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefa_descricao_alter_tarefa_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal/Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], max_length=10),
        ),
    ]
